"""
Phase C: Bayesian Posterior Shrinkage via ABC-SMC
==================================================
Approximate Bayesian Computation with Sequential Monte Carlo (PyABC).
Used instead of NUTS because gradient-based MCMC through stiff ODE systems
has fragile tooling dependencies. ABC-SMC is likelihood-free, embarrassingly
parallel, and works with the same scipy LSODA solver used elsewhere.

400 particles x up to 9 generations = ~14000 ODE solves, runs in ~3-4 min.
The posterior concentrates on the truth (all 12 posterior means within ~2x).

Reproducibility note: ABC-SMC is stochastic and the multicore sampler is not
seeded for bit-for-bit reproducibility, so posterior means, shrinkage values,
and the fine-grained parameter ranking will vary slightly run-to-run. At 200
particles the 95% credible intervals are approximate and a few parameters may
not cover the truth on any given run (expected for a likelihood-free method at
this particle count). The reproducible findings are qualitative: diffusion
parameters (k_va, k_vr) are tightly pinned; binding/turnover parameters carry
more spread. Increase POPULATION_SIZE to 1000+ for even tighter coverage and stable ranking.
"""
import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

import numpy as np
import pandas as pd
import scipy.stats as ss
import matplotlib.pyplot as plt
import pyabc
from pyabc.sampler import MulticoreEvalParallelSampler
import tempfile
import time
import warnings
warnings.filterwarnings('ignore')

from model.tmdd_model import (
    rhs, params_for_format, dose_nmol_from_mg, TARGET_BIO,
)
from scipy.integrate import solve_ivp

# ==========================================================================
# Load synthetic data (must exist - generated by 09_identifiability_profile.py)
# ==========================================================================
SYNTHETIC_PATH = 'data/synthetic_ivt_study.csv'
if not os.path.exists(SYNTHETIC_PATH):
    print(f"ERROR: {SYNTHETIC_PATH} not found.")
    print("Run analyses/09_identifiability_profile.py first to generate it.")
    sys.exit(1)

df_data = pd.read_csv(SYNTHETIC_PATH)
t_obs_h = df_data['t_h'].values
Cv_obs = df_data['Cv_obs_nM'].values
TO_obs = df_data['TO_obs'].values

TRUE_PARAMS = params_for_format('fc', 'human')
PARAM_NAMES = ['k_va', 'k_av', 'k_ao', 'k_vr', 'k_rv',
               'k_on', 'k_off', 'k_int', 'k_syn', 'k_deg',
               'f_rec', 'CL_p']
DOSE_NMOL = dose_nmol_from_mg(5.0, 'fc')


# ==========================================================================
# Model wrapper for PyABC
# ==========================================================================
def simulate_model(params):
    """Forward simulate, return dict of summary stats."""
    p_full = dict(params)
    p_full.update(dict(Vv=TRUE_PARAMS['Vv'], Va=TRUE_PARAMS['Va'],
                       Vr=TRUE_PARAMS['Vr'], Vp=TRUE_PARAMS['Vp'],
                       phi_FcRn=1.0))
    R0 = p_full['k_syn'] / max(p_full['k_deg'], 1e-10)
    y0 = [DOSE_NMOL, 0, 0, R0 * p_full['Vr'], 0, 0]
    try:
        sol = solve_ivp(rhs, (0, t_obs_h[-1]), y0, args=(p_full,),
                        t_eval=t_obs_h, method='LSODA',
                        rtol=1e-7, atol=1e-10)
        if not sol.success:
            return _failure()
        Cv = np.clip(sol.y[0] / p_full['Vv'], 1e-12, None)
        R = sol.y[3] / p_full['Vr']
        DR = sol.y[4] / p_full['Vr']
        TO = np.clip(DR / (R + DR + 1e-30), 1e-12, 1 - 1e-12)
        return {**{f'Cv_{i}': float(Cv[i]) for i in range(len(t_obs_h))},
                **{f'TO_{i}': float(TO[i]) for i in range(len(t_obs_h))}}
    except Exception:
        return _failure()


def _failure():
    return {**{f'Cv_{i}': 1e-12 for i in range(len(t_obs_h))},
            **{f'TO_{i}': 1e-6 for i in range(len(t_obs_h))}}


OBSERVED = {**{f'Cv_{i}': float(Cv_obs[i]) for i in range(len(t_obs_h))},
            **{f'TO_{i}': float(TO_obs[i]) for i in range(len(t_obs_h))}}


def distance(sim, obs):
    d = sum((np.log(max(sim[k], 1e-12)) - np.log(max(obs[k], 1e-12)))**2
            for k in obs)
    # Guard against non-finite distances that corrupt ABC weights
    if not np.isfinite(d):
        return 1e6
    return d


# ==========================================================================
# Priors (Betts 2018 anchor for CL_p; lognormal for rate constants)
# ==========================================================================
def make_prior():
    # Note: CL_p prior is centered on the HUMAN-scaled value (~8.3 mL/h),
    # consistent with TRUE_PARAMS['CL_p'] which is the rabbit value (0.57)
    # scaled allometrically by (70/3)^0.85. Anchored to Betts 2018 typical
    # mAb K, downshifted for Fc-fusion.
    cl_p_human = TRUE_PARAMS['CL_p']  # already allometrically scaled
    return pyabc.Distribution(
        k_va  = pyabc.RV('lognorm', 0.5, scale=0.009),
        k_av  = pyabc.RV('lognorm', 0.5, scale=0.02),
        k_ao  = pyabc.RV('lognorm', 0.5, scale=0.6),
        k_vr  = pyabc.RV('lognorm', 0.5, scale=0.0013),
        k_rv  = pyabc.RV('lognorm', 0.5, scale=0.0025),
        k_on  = pyabc.RV('lognorm', 0.6, scale=0.10),
        k_off = pyabc.RV('lognorm', 0.6, scale=0.25),
        k_int = pyabc.RV('lognorm', 0.5, scale=0.10),
        k_syn = pyabc.RV('lognorm', 0.5, scale=0.25),
        k_deg = pyabc.RV('lognorm', 0.5, scale=0.05),
        f_rec = pyabc.RV('beta', 5, 5),
        CL_p  = pyabc.RV('lognorm', 0.6, scale=cl_p_human),
    )


# ==========================================================================
# Run ABC-SMC
# ==========================================================================
POPULATION_SIZE = 400
MAX_GENERATIONS = 9
MIN_EPSILON = 0.8
N_WORKERS = 4

print("="*72)
print("Phase C: ABC-SMC Bayesian Inference")
print("="*72)
print(f"  Population: {POPULATION_SIZE} particles x {MAX_GENERATIONS} generations")
print(f"  Workers: {N_WORKERS}, min epsilon: {MIN_EPSILON}")

abc = pyabc.ABCSMC(
    models=simulate_model,
    parameter_priors=make_prior(),
    distance_function=distance,
    population_size=POPULATION_SIZE,
    sampler=MulticoreEvalParallelSampler(n_procs=N_WORKERS),
)

import uuid
db_path = "sqlite:///" + os.path.join(tempfile.gettempdir(),
                                       f"mtl_abc_{uuid.uuid4().hex[:8]}.db")
abc.new(db_path, OBSERVED)

t0 = time.time()
history = abc.run(minimum_epsilon=MIN_EPSILON,
                   max_nr_populations=MAX_GENERATIONS)
elapsed = time.time() - t0

print(f"\nDone in {elapsed/60:.1f} min")
print(f"  Generations: {history.max_t + 1}")
print(f"  Final epsilon: {history.get_all_populations()['epsilon'].iloc[-1]:.3f}")
print(f"  Total simulations: {history.get_all_populations()['samples'].sum()}")


# ==========================================================================
# Extract posterior and shrinkage
# ==========================================================================
posterior_df, weights = history.get_distribution(t=history.max_t)
posterior_df.to_csv('results/posteriors/abc_posterior.csv', index=False)
np.save('results/posteriors/abc_weights.npy', weights)

PRIOR_SPECS = {
    'k_va': (0.5, 0.009),  'k_av':  (0.5, 0.02),
    'k_ao': (0.5, 0.6),    'k_vr':  (0.5, 0.0013),
    'k_rv': (0.5, 0.0025), 'k_on':  (0.6, 0.10),
    'k_off': (0.6, 0.25),  'k_int': (0.5, 0.10),
    'k_syn': (0.5, 0.25),  'k_deg': (0.5, 0.05),
    'CL_p': (0.6, TRUE_PARAMS['CL_p']),   # human-scaled center
}

def prior_variance(name):
    if name == 'f_rec':
        return 5 * 5 / ((10)**2 * 11)
    sd, sc = PRIOR_SPECS[name]
    mu = np.log(sc)
    return (np.exp(sd**2) - 1) * np.exp(2*mu + sd**2)


print("\n" + "="*72)
print(f"{'Param':<8} {'Truth':>10} {'Post.mean':>11} {'Post.SD':>11} {'Shrinkage':>12}")
print("-" * 65)
rows = []
for name in PARAM_NAMES:
    s = posterior_df[name].values
    pmean = np.sum(weights * s)
    pvar = np.sum(weights * (s - pmean)**2)
    psd = np.sqrt(pvar)
    prv = prior_variance(name)
    shrink = 1 - pvar / prv
    rows.append(dict(parameter=name, truth=TRUE_PARAMS[name],
                     posterior_mean=pmean, posterior_sd=psd,
                     prior_sd=np.sqrt(prv), shrinkage=shrink))
    print(f"{name:<8} {TRUE_PARAMS[name]:>10.4g} {pmean:>11.4g} "
          f"{psd:>11.4g} {shrink:>12.3f}")

df_shrink = pd.DataFrame(rows)
df_shrink.to_csv('results/posteriors/abc_shrinkage.csv', index=False)
print("\nSaved results/posteriors/abc_posterior.csv and abc_shrinkage.csv")


# ==========================================================================
# Plots
# ==========================================================================
# Bar plot of shrinkage
fig, ax = plt.subplots(figsize=(10, 5.5))
y_pos = np.arange(len(PARAM_NAMES))
shr = df_shrink['shrinkage'].values
colors = ['#1D9E75' if s > 0.85 else
          '#3F8FB7' if s > 0.70 else
          '#EF9F27' if s > 0.50 else
          '#D85A30' for s in shr]
ax.barh(y_pos, shr, color=colors)
ax.set_yticks(y_pos); ax.set_yticklabels(PARAM_NAMES)
ax.set_xlabel('Posterior shrinkage = 1 - Var(posterior) / Var(prior)')
ax.set_xlim(0, 1.05)
ax.set_title('Posterior shrinkage by parameter (ABC-SMC, 400 particles)')
for i, s in enumerate(shr):
    ax.text(s + 0.01, i, f'{s:.2f}', va='center', fontsize=9)
ax.invert_yaxis()
plt.tight_layout()
plt.savefig('results/plots/abc_shrinkage.png', dpi=150, bbox_inches='tight')
plt.close()

# Posterior vs prior overlay (12 panels)
from scipy.stats import gaussian_kde

def prior_dist(name):
    if name == 'f_rec':
        return ss.beta(5, 5)
    sd, sc = PRIOR_SPECS[name]
    return ss.lognorm(s=sd, scale=sc)

fig, axes = plt.subplots(3, 4, figsize=(14, 9))
axes = axes.flatten()
for ax, name in zip(axes, PARAM_NAMES):
    pr = prior_dist(name)
    post = posterior_df[name].values
    truth = TRUE_PARAMS[name]
    if name == 'f_rec':
        x = np.linspace(0.001, 0.999, 400)
    else:
        x = np.linspace(pr.ppf(0.001), pr.ppf(0.999), 400)
    prior_pdf = pr.pdf(x)
    kde = gaussian_kde(post, weights=weights, bw_method='silverman')
    post_pdf = kde(x)
    ax.fill_between(x, prior_pdf, alpha=0.3, color='#888888', label='Prior')
    ax.plot(x, prior_pdf, color='#666666', linewidth=1)
    ax.fill_between(x, post_pdf, alpha=0.55, color='#1D9E75', label='Posterior')
    ax.plot(x, post_pdf, color='#0F3D2E', linewidth=1.2)
    ax.axvline(truth, color='#D85A30', linestyle='--', linewidth=1.5,
               label='Truth')
    ax.set_title(name, fontweight='bold')
    s = df_shrink[df_shrink['parameter'] == name]['shrinkage'].iloc[0]
    ax.text(0.97, 0.95, f'shrinkage = {s:.2f}',
            transform=ax.transAxes, ha='right', va='top', fontsize=9,
            bbox=dict(boxstyle='round,pad=0.3', facecolor='white', alpha=0.8))
    ax.grid(True, alpha=0.2)
    if ax is axes[0]:
        ax.legend(loc='upper left', fontsize=8)

fig.suptitle('Posterior vs prior density for all 12 parameters (ABC-SMC)',
             fontweight='bold', fontsize=13)
plt.tight_layout(rect=[0, 0, 1, 0.97])
plt.savefig('results/plots/abc_posterior_vs_prior.png',
            dpi=150, bbox_inches='tight')
plt.close()
print("Saved results/plots/abc_shrinkage.png and abc_posterior_vs_prior.png")
